### ISSUE TITLE
Support maintenance mode stores

### ISSUE THREAD

**Issue by byjord** [bigcartel/dugway#98] opened 2014-01-30 16:18 UTC
We need support for stores that are being customized and have had maintenance turned on.

I understand the reason for this being off would be to stop people from loading store items whilst the store owners are inputting new products - but we need this option placed into the code.

Maybe with an auth system for maintenance mode stores?

**Comment by mjw-keenan** [comment] 2015-09-15 01:59
Another +1 for this feature. Would be very useful

**Comment by callumlocke** [comment] 2016-06-07 21:54
Any progress since September 2015? Any workaround?

**Comment by nickendle** [comment] 2016-07-01 16:01
@callumlocke sorry for the delay in getting back to you. Unfortunately there's no news on this - it's still possible that support will be added down the road, but it doesn't seem likely anytime soon. 

Closing this as it's a duplicate of #92.

**Closed by nickendle** 2016-07-01 16:01 UTC
Labels: enhancement
