### ISSUE TITLE
Can't run dugway

### ISSUE THREAD

**Issue by goncalth** [bigcartel/dugway#164] opened 2019-03-26 13:31 UTC
Hi there, I'm really interested in using Dugway but when i create a theme or try to run the `dugway server` command, I get the following error:

> `C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/liquid-2.4.1/lib/liquid/htmltags.rb:43: warning: key "index0" is duplicated and overwritten on line 46
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
Traceback (most recent call last):
        40: from C:/Ruby25-x64/bin/dugway:23:in `<main>'
        39: from C:/Ruby25-x64/bin/dugway:23:in `load'
        38: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/dugway-0.11.1/bin/dugway:7:in `<top (required)>'
        37: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.17.0/lib/thor/base.rb:434:in `start'
        36: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.17.0/lib/thor.rb:344:in `dispatch'
        35: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.17.0/lib/thor/invocation.rb:120:in `invoke_task'
        34: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.17.0/lib/thor/task.rb:27:in `run'
        33: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.17.0/lib/thor.rb:32:in `block in register'
        32: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.17.0/lib/thor/invocation.rb:109:in `invoke'
        31: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.17.0/lib/thor/group.rb:238:in `dispatch'
        30: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.17.0/lib/thor/invocation.rb:126:in `invoke_all'
        29: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.17.0/lib/thor/invocation.rb:126:in `map'
        28: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.17.0/lib/thor/invocation.rb:126:in `each'
        27: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.17.0/lib/thor/invocation.rb:126:in `block in invoke_all'
        26: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.17.0/lib/thor/invocation.rb:120:in `invoke_task'
        25: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.17.0/lib/thor/task.rb:27:in `run'
        24: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/dugway-0.11.1/lib/dugway/cli/server.rb:25:in `start'
        23: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rack-1.4.7/lib/rack/server.rb:137:in `start'
        22: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rack-1.4.7/lib/rack/server.rb:268:in `start'
        21: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rack-1.4.7/lib/rack/server.rb:272:in `server'
        20: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `get'
        19: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `inject'
        18: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `each'
        17: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `block in get'
        16: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `const_get'
        15: from C:/Ruby25-x64/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        14: from C:/Ruby25-x64/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        13: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rack-1.4.7/lib/rack/handler/thin.rb:1:in `<top (required)>'
        12: from C:/Ruby25-x64/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        11: from C:/Ruby25-x64/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        10: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thin-1.5.1/lib/thin.rb:7:in `<top (required)>'
         9: from C:/Ruby25-x64/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:34:in `require'
         8: from C:/Ruby25-x64/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
         7: from C:/Ruby25-x64/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:130:in `require'
         6: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7-x64-mingw32/lib/eventmachine.rb:8:in `<top (required)>'
         5: from C:/Ruby25-x64/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:34:in `require'
         4: from C:/Ruby25-x64/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
         3: from C:/Ruby25-x64/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:130:in `require'
         2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7-x64-mingw32/lib/rubyeventmachine.rb:2:in `<top (required)>'
         1: from C:/Ruby25-x64/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/Ruby25-x64/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- 2.5/rubyeventmachine (LoadError)`

I searched here and there for a fix but I can't find one, and editing bigcartel themes without this tool is such a pain.

Thanks for your help

**Comment by brettchalupa** [comment] 2019-03-26 22:55
@goncalth Thanks for reporting this. It's a duplicate of https://github.com/bigcartel/dugway/issues/163, so I'm going to close this and keep the conversation in that thread. Hoping to have a fix for this ready in the coming days.

**Closed by brettchalupa** 2019-03-26 22:55 UTC

**Comment by brettchalupa** [comment] 2019-04-04 19:43
Following up to share that this should work:

```
gem uninstall eventmachine
gem install --platform ruby eventmachine
```

The problem is that on Windows that gem runs into some trouble with `dugway server`. So by specifying the platform, it'll work.
